version: 2.1
jobs:
  build-job:
    docker:
      image: circleci/openjdk:17
    steps:
      - checkout
      - run:
          name: Build
          command: mvn clean install

  test-job:
    docker:
      image: circleci/openjdk:17
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test

  report-job:
    docker:
      image: circleci/openjdk:17
    steps:
      - checkout
      - run:
          name: Report
          command: mvn allure:report
      - run:
          name: View Report
          command: allure serve target/allure-results
